/**
 * Thin stubs for the Foundry-only packages.
 *
 * In Foundry, `@foundry/functions-api` and `@foundry/ontology-api` are
 * provided by the runtime. Locally they don't exist, so we alias both
 * package specifiers to this file via `tsconfig.paths` (for typechecking)
 * and `vite.resolve.alias` (for tests).
 *
 * Only the surface the V2 adapter touches is stubbed. Add new symbols as
 * adapters need them.
 */

// --- decorators --------------------------------------------------------
// Foundry's V2 decorators register a function as exposed to the ontology
// runtime. Locally they are no-ops.
export function Function(): MethodDecorator {
  return () => {};
}
export function OntologyEditFunction(): MethodDecorator {
  return () => {};
}
export function Edits(_objectType: unknown): MethodDecorator {
  return () => {};
}

// --- numeric primitives ------------------------------------------------
// Foundry distinguishes `Integer` from `Double`/`Float`; the TS runtime
// has only `number`. We alias `Integer` so V1-style signatures port over
// without flagging type errors.
export type Integer = number;

// --- timestamps --------------------------------------------------------
export class Timestamp {
  constructor(private readonly _ms: number) {}
  static now(): Timestamp {
    return new Timestamp(Date.now());
  }
  static fromISOString(iso: string): Timestamp {
    return new Timestamp(new Date(iso).getTime());
  }
  valueOf(): number {
    return this._ms;
  }
  toISOString(): string {
    return new Date(this._ms).toISOString();
  }
}

/**
 * LocalDate stub — represents a calendar date without time-of-day. In
 * Foundry, `LocalDate` is comparable and supports `now()`. Locally we
 * back it with the start-of-day epoch ms so numeric `valueOf()` based
 * comparisons (V1 uses `>=`) work.
 */
export class LocalDate {
  constructor(private readonly _startOfDayMs: number) {}
  static now(): LocalDate {
    const d = new Date();
    return new LocalDate(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
  }
  static fromEpochMs(ms: number): LocalDate {
    return new LocalDate(ms);
  }
  static fromISOString(iso: string): LocalDate {
    return new LocalDate(new Date(iso).getTime());
  }
  valueOf(): number {
    return this._startOfDayMs;
  }
  toISOString(): string {
    return new Date(this._startOfDayMs).toISOString();
  }
}

// --- notification builders --------------------------------------------
// Foundry's notification API uses chainable builders to construct an
// `EmailNotificationContent` + `ShortNotification` envelope. Locally we
// stub the chain so adapter typecheck passes; the actual delivery
// happens in Foundry.

export class EmailNotificationContent {
  constructor(public readonly subject: string, public readonly body: string) {}
  static builder() {
    let _subject = "";
    let _body = "";
    const b = {
      subject(s: string) { _subject = s; return b; },
      body(s: string) { _body = s; return b; },
      build(): EmailNotificationContent { return new EmailNotificationContent(_subject, _body); },
    };
    return b;
  }
}

export class ShortNotification {
  constructor(public readonly heading: string, public readonly content: string) {}
  static builder() {
    let _heading = "";
    let _content = "";
    const b = {
      heading(s: string) { _heading = s; return b; },
      content(s: string) { _content = s; return b; },
      build(): ShortNotification { return new ShortNotification(_heading, _content); },
    };
    return b;
  }
}

export class Notification {
  constructor(
    public readonly shortNotification: ShortNotification,
    public readonly emailNotificationContent: EmailNotificationContent,
  ) {}
  static builder() {
    let _short: ShortNotification | undefined;
    let _email: EmailNotificationContent | undefined;
    const b = {
      shortNotification(s: ShortNotification) { _short = s; return b; },
      emailNotificationContent(e: EmailNotificationContent) { _email = e; return b; },
      build(): Notification {
        return new Notification(
          _short ?? new ShortNotification("", ""),
          _email ?? new EmailNotificationContent("", ""),
        );
      },
    };
    return b;
  }
}

// --- functions map (Workshop-style key→value return) ------------------
export class FunctionsMap<K, V> {
  private readonly _backing = new Map<unknown, V>();
  set(key: K, value: V): void {
    this._backing.set(key as unknown, value);
  }
  get(key: K): V | undefined {
    return this._backing.get(key as unknown);
  }
  entries(): IterableIterator<[K, V]> {
    return this._backing.entries() as IterableIterator<[K, V]>;
  }
  get size(): number {
    return this._backing.size;
  }
}

// --- ontology object stubs --------------------------------------------
// Real types are generated by Foundry per-ontology. Locally we mirror
// just enough of the V1 `Ufoentry` and `UfoFsr` shape to keep the
// adapter typecheck happy. Tests do not exercise these.
//
// Declared as classes (not interfaces) so the symbol exists at runtime
// — `@Edits(Ufoentry)` passes the class as a value, which only works
// because TypeScript class declarations produce both a type and a value.

export interface ObjectSet<T> {
  all(): T[];
  filter(predicate: (item: T) => unknown): ObjectSet<T>;
  /** Foundry returns these async; stub mirrors the signature so adapter typecheck passes. */
  max<V>(selector: (item: T) => V | undefined): Promise<V | undefined>;
  min<V>(selector: (item: T) => V | undefined): Promise<V | undefined>;
  orderBy<V>(selector: (item: T) => { desc(): V; asc(): V }): ObjectSet<T>;
  take(n: number): T[];
}

function emptyObjectSet<T>(): ObjectSet<T> {
  const s: ObjectSet<T> = {
    all: () => [],
    filter: () => s,
    max: async () => undefined,
    min: async () => undefined,
    orderBy: () => s,
    take: () => [],
  };
  return s;
}

export class Ufoentry {
  // Identity & classification
  idDossier?: string;
  internalId?: string;
  domain?: string;
  title?: string;
  label?: string;
  channel?: string;
  isMigrated?: boolean;
  status?: string;
  // Aircraft
  programLetter?: string;
  program?: string;
  aircraftId?: string;
  skywiseAircraftId?: string;
  isappforAllMsn?: boolean;
  msn?: number;
  aircraftType?: string;
  aircraftModel?: string;
  regNumber?: string;
  craftFlighthrs?: number;
  craftFlightcycs?: number;
  operIcao?: string;
  // Component / powerplant
  engineSeries?: string;
  engineModel?: string;
  compSerialNum?: string;
  compPartNum?: string;
  compFlightcycs?: number;
  compFlightHrs?: number;
  compFin?: string;
  // ATA
  ataChap?: number;
  ata4d?: number;
  // Parties
  dossReqIcao?: string;
  dossVisIcao?: string;
  // Lifecycle dates (timestamps in the V1 ontology; toISOString() at read time)
  dossCreDate?: Timestamp;
  dossUpDate?: Timestamp;
  dossSubDate?: Timestamp;
  dossClosDate?: Timestamp;
  newRequestDate?: Timestamp;
  // Message rollups
  nbTotalMess?: number;
  nbClosedMess?: number;
  highestMessUrg?: string;
  messOpen?: boolean;
  hasAppDoc?: boolean;
  appDocType?: string;
  // FSR-driven
  aircraftStatus?: string;
  focal?: string;
  trStatus?: string;
  rts?: LocalDate;
  msnRts?: LocalDate;
  customerEscalation?: boolean;
  internalEscalation?: boolean;
  partsEscalation?: boolean;
  // Priority surface
  globalPriorityScore?: number;
  sbcbump?: number;
  // Comments (Comments V2 spike)
  comments?: string[];
  linkedComments?: string[];
  lastPartsComment?: Timestamp;
  lastTechComment?: Timestamp;
  lastCustComment?: Timestamp;
  isFavorite?: boolean;
}

export class UfoFsr {
  userId?: string;
  name?: string;
  operatorCode?: string;
  lastLogIn?: Timestamp;
  postCommentFlag?: boolean;
  favorites?: string[];
  ufoescalations: ObjectSet<Ufoescalation> = emptyObjectSet<Ufoescalation>();
  delete(): void { /* stub */ }
}

export class Fsrteam {
  teamId?: string;
  teamName?: string;
  operator?: string;
  operatorCode?: string;
  members?: string[];
  comments?: string[];
  watchList?: string[];
  ufofsrs: ObjectSet<UfoFsr> = emptyObjectSet<UfoFsr>();
}

/**
 * V2 stub retains V1 column spelling `escalationRasisedDate` (misspelled
 * as `Rasised`) because that is the actual materialized property. The
 * rename is Phase-3 ontology re-shape work, tracked separately.
 */
export class Ufoescalation {
  escalationId?: string;
  user?: string;
  escalationType?: string;
  dossierId?: string;
  escalationRasisedDate?: LocalDate;
}

export class LogFsrinputDriver {
  actionRid?: string;
  actionTimestamp?: Timestamp;
  ufoentry?: string[];
}

/**
 * `PriorityAlgorithm` stub. Hybrid V2 shape per the port direction:
 * Spec §4.13 wrapper (`algorithmId`, `algorithmName`, `mainConfigFlag`,
 * `updatedAt`, `updatedBy`) plus a `parameters` array that preserves V1's
 * tier/span machinery inside an ordered V2 struct. Position in the array
 * drives weighting — index 0 is highest priority, mirroring V1's
 * `priorityParameter1`.
 *
 * Existing V1 `PriorityAlgorithm` instances (60 flat properties) are
 * migrated to this shape at the Ontology layer before the V2 binding
 * goes live; the V2 driver never sees the V1 flat shape.
 */
export interface ParameterEntry {
  /** V2 parameter key, e.g. `"operator_code_icao"`. The parameter table in
   *  `prioritization/parameters.ts` maps the key to a kind + reader. */
  key: string;
  /** True iff this parameter should be scored as a span over the entry
   *  set's dynamic min/max for the read field. False = tier-based scoring
   *  using `tiers`. */
  isSpan: boolean;
  /** Up to 5 strings; index 0 is highest tier. Ignored when `isSpan` is true. */
  tiers: string[];
}

export class PriorityAlgorithm {
  algorithmId?: string;
  algorithmName?: string;
  /** 1 = active configuration; 0 = inactive. Exactly one
   *  `PriorityAlgorithm` should have value 1 at any time. */
  mainConfigFlag?: number;
  parameters?: ParameterEntry[];
  updatedAt?: Timestamp;
  updatedBy?: string;
}

export const Objects = {
  search: () => ({
    ufoentry: () => ({
      filter: (_: (e: Ufoentry) => unknown): ObjectSet<Ufoentry> => emptyObjectSet<Ufoentry>(),
      all: (): Ufoentry[] => [],
    }),
    ufoFsr: () => ({
      filter: (_: (f: UfoFsr) => unknown): ObjectSet<UfoFsr> => emptyObjectSet<UfoFsr>(),
      all: (): UfoFsr[] => [],
    }),
    fsrteam: () => ({
      filter: (_: (t: Fsrteam) => unknown): ObjectSet<Fsrteam> => emptyObjectSet<Fsrteam>(),
      all: (): Fsrteam[] => [],
    }),
    logFsrinputDriver: () => ({
      filter: (_: (l: LogFsrinputDriver) => unknown): ObjectSet<LogFsrinputDriver> => emptyObjectSet<LogFsrinputDriver>(),
      all: (): LogFsrinputDriver[] => [],
    }),
    priorityAlgorithm: () => ({
      filter: (_: (a: PriorityAlgorithm) => unknown): ObjectSet<PriorityAlgorithm> => emptyObjectSet<PriorityAlgorithm>(),
      all: (): PriorityAlgorithm[] => [],
    }),
  }),
};
