/**
 * Thin stubs for the Foundry-only packages.
 *
 * In Foundry, `@foundry/functions-api` and `@foundry/ontology-api` are
 * provided by the runtime. Locally they don't exist, so we alias both
 * package specifiers to this file via `tsconfig.paths` (for typechecking)
 * and `vite.resolve.alias` (for tests).
 *
 * Only the surface the V2 adapter touches is stubbed. Add new symbols as
 * adapters need them.
 */

// --- decorators --------------------------------------------------------
// Foundry's V2 decorators register a function as exposed to the ontology
// runtime. Locally they are no-ops.
export function Function(): MethodDecorator {
  return () => {};
}
export function OntologyEditFunction(): MethodDecorator {
  return () => {};
}
export function Edits(_objectType: unknown): MethodDecorator {
  return () => {};
}

// --- timestamps --------------------------------------------------------
export class Timestamp {
  constructor(private readonly _ms: number) {}
  static now(): Timestamp {
    return new Timestamp(Date.now());
  }
  static fromISOString(iso: string): Timestamp {
    return new Timestamp(new Date(iso).getTime());
  }
  valueOf(): number {
    return this._ms;
  }
  toISOString(): string {
    return new Date(this._ms).toISOString();
  }
}

// --- functions map (Workshop-style key→value return) ------------------
export class FunctionsMap<K, V> {
  private readonly _backing = new Map<unknown, V>();
  set(key: K, value: V): void {
    this._backing.set(key as unknown, value);
  }
  get(key: K): V | undefined {
    return this._backing.get(key as unknown);
  }
  entries(): IterableIterator<[K, V]> {
    return this._backing.entries() as IterableIterator<[K, V]>;
  }
  get size(): number {
    return this._backing.size;
  }
}

// --- ontology object stubs --------------------------------------------
// Real types are generated by Foundry per-ontology. Locally we mirror
// just enough of the V1 `Ufoentry` and `UfoFsr` shape to keep the
// adapter typecheck happy. Tests do not exercise these.
//
// Declared as classes (not interfaces) so the symbol exists at runtime
// — `@Edits(Ufoentry)` passes the class as a value, which only works
// because TypeScript class declarations produce both a type and a value.

export class Ufoentry {
  idDossier?: string;
  comments?: string[];
  linkedComments?: string[];
  lastPartsComment?: Timestamp;
  lastTechComment?: Timestamp;
  lastCustComment?: Timestamp;
  operIcao?: string;
  isFavorite?: boolean;
}

export class UfoFsr {
  name?: string;
  lastLogIn?: Timestamp;
  postCommentFlag?: boolean;
  favorites?: string[];
  delete(): void { /* stub */ }
}

export interface ObjectSet<T> {
  all(): T[];
  filter(predicate: (item: T) => unknown): ObjectSet<T>;
}

export const Objects = {
  search: () => ({
    ufoentry: () => ({
      filter: (_: (e: Ufoentry) => unknown): ObjectSet<Ufoentry> => ({
        all: () => [],
        filter: () => Objects.search().ufoentry().filter(_),
      }),
      all: (): Ufoentry[] => [],
    }),
    ufoFsr: () => ({
      filter: (_: (f: UfoFsr) => unknown): ObjectSet<UfoFsr> => ({
        all: () => [],
        filter: () => Objects.search().ufoFsr().filter(_),
      }),
      all: (): UfoFsr[] => [],
    }),
  }),
};
